// apps/states-of-matter/frontend/src/modals/Transfer.svelte
<script lang="ts">
  import {onMount} from "svelte";
  import {eccService, socketService} from "services";
  import {accountStore, modalStore} from "stores";
  import Modal from "../ui/Modal.svelte";

  const token = $modalStore.data;

  let to = "";
  let quantity = 0;
  let memo = "";
  let isWithdraw = false;

  const errors = {
    name: {
      value: true,
      length: true,
      valid: true
    },
    quantity: {
      value: true,
      min: true,
      decimals: true,
      balance: true,
    }
  };

  let isEnoughForFee = true;
  let disabled = true;

  let remaining = "";
  let total = "";

  const getTotal = (): void => {
    total = (quantity ? quantity : 0.0000).toFixed(4);
  };

  const tlosBalance = (): string => {
    const {fungible} = $accountStore.wallet;
    const token = fungible.find(({symbol}) => symbol === "TLOS");

    if (!token) {
      return "0.0000";
    }

    return parseFloat(token.liquid).toFixed(4);
  };

  const getFee = (): void => {
    const balanceFloat = parseFloat(tlosBalance());
    const feeFloat = parseFloat("0.1000");
    const total = balanceFloat - feeFloat;
    const isValidBalanceFee = total >= 0;

    isEnoughForFee = isValidBalanceFee;
  };

  const getRemaining = (): void => {
    const vmt = $accountStore.wallet.fungible.find(({symbol}) => symbol === token.symbol);
    const {liquid} = vmt;

    remaining = (parseFloat(liquid) - parseFloat(`${quantity}` ? `${quantity}` : `0.0000 ${token.symbol}`)).toFixed(4);
  };

  const onInput = (): void => {
    errors.quantity.value = quantity !== null;
    errors.quantity.min = quantity >= 0.0001;
    errors.quantity.decimals = (quantity.toString().split(".")[1] || []).length <= 4;
    errors.name.value = to !== null;
    errors.name.length = to.length >= 3;
    errors.name.valid = /^[a-z1-5.\s]*$/.test(to);

    disabled = !errors.quantity.value || !errors.quantity.min || errors.quantity.decimals;

    const balancee = parseFloat($modalStore.data.liquid);
    const total = balancee - quantity;

    errors.quantity.balance = total >= 0;

    getRemaining();
    getTotal();
    getFee();
  };

  const onChange = (): void => {
    onInput();
  };

  const onTransfer = (): void => {
    const {name, nonce, privateKey} = $accountStore.profile;
    const signature = eccService.sign(`${nonce}`, privateKey);
    const from = name;

    socketService.socket.emit("transferToken", {
      from,
      to,
      quantity: {
        contract: $modalStore.data.contract,
        quantity: `${quantity.toFixed(4)} ${$modalStore.data.symbol}`
      },
      memo,
      signature,
      isWithdraw
    });
  };

  onMount(() => {
    getRemaining();
    getTotal();
    getFee();
  })
</script>

<style>
  h1 {
    margin: 0;
    margin-bottom: var(--spacing-md);
    font-size: 24px;
    font-weight: 900;
  }

  p {
    margin: 0;
    margin-bottom: var(--spacing-md);
    line-height: 1.4;
  }

  .transfer {
    width: 320px;
  }

  img {
    height: 16px;
    width: 16px;
    /* vertical-align: super; */
  }

  .info {
    margin-bottom: var(--spacing-md);
    padding: var(--spacing-sm);
    line-height: 1.4;
    border: 1px solid;
    border-right: 0;
    border-left: 0;
    border-image: linear-gradient(
      90deg,
      rgba(63, 63, 63, 1) 0%,
      rgba(255, 255, 255, 1) 50%,
      rgba(63, 63, 63, 1) 100%
    ) 1;
  }

  .amt {
    display: flex;
    justify-content: space-between;
  }

  .error {
    margin: var(--spacing-md);
    color: rgb(var(--red));
  }

  .submit-batn {
    width: 100%;
    display: flex;
    justify-content: center;
  }
</style>

<Modal>
  <div class="transfer">
    <h1>Transfer</h1>
    <p>
      Transfer tokens to another Eternitas account or to a Telos account.
    </p>

    <form id="transferForm" on:submit|preventDefault={onTransfer}>

      <label>
        <div class="label-body">To</div>
        <input
          placeholder="To"
          maxlength="12"
          required
          bind:value={to}
          on:input={onInput}
          on:change={onChange}
        />
      </label>

      {#if !errors.name.value}
        <div class="error">Mustn't be empty.</div>
      {/if}
      {#if !errors.name.length}
        <div class="error">Must contain at least 3 characters</div>
      {/if}
      {#if !errors.name.valid}
        <div class="error">Must only contain a-z, 1-5 and . (dot).</div>
      {/if}

      <label>
        <div>Quantity</div>
        <input
          placeholder="Quantity"
          type="number"
          step="0.0001"
          bind:value={quantity}
          on:input={onInput}
          on:change={onChange}
        />
      </label>
      <!-- <a matSuffix class="set-max" (click)="setMax()">MAX</a> -->
      {#if !errors.quantity.value}
        <div class="error">Mustn't be empty.</div>
      {/if}
      {#if !errors.quantity.decimals}
        <div class="error">Up to four decimal places allowed.</div>
      {/if}
      {#if !errors.quantity.balance}
        <div class="error">Insufficient balance.</div>
      {/if}
      {#if !isEnoughForFee}
        <div class="error">Insufficient balance to pay the fees.</div>
      {/if}
      {#if !errors.quantity.min}
        <div class="error">Minimum 0.0001 VMT.</div>
      {/if}

      <label>
        <div>Memo</div>
        <input placeholder="Memo" maxlength="256" bind:value={memo}>
      </label>

      <label class="label--checkbox">
        <input type="checkbox" bind:checked={isWithdraw}/>
        <div>Transfer to Telos account</div>
      </label>

    </form>

    <div class="info">
      <div class="amt">
        <span>FEE</span>
        <span>0.1000 <img src="assets/currencies/TLOS.png" alt="TLOS"/></span>
      </div>
      <div class="amt">
        <span>REMAINING</span>
        <span>{tlosBalance()} <img src="assets/currencies/TLOS.png" alt="TLOS"/></span>
      </div>
      <br/>
      <div class="amt">
        <span>TRANSFER</span>
        <span>{total} <img src="assets/currencies/{token.symbol}.png" alt={token.symbol}/></span>
      </div>
      <div class="amt">
        <span>REMAINING</span>
        <span>{remaining} <img src="assets/currencies/{token.symbol}.png" alt={token.symbol}/></span>
      </div>
    </div>

    <div class="submit-batn">
      <button form="transferForm">
        TRANSFER
      </button>
    </div>
  </div>
</Modal>

// apps/svm-wallet/frontend/src/app/views/wallet/dialogs/transfer.component.ts
import {Component, Inject} from "@angular/core";
import {FormBuilder, FormControl, Validators} from "@angular/forms";
import {MAT_DIALOG_DATA} from "@angular/material/dialog";
import {MatSnackBar} from "@angular/material/snack-bar";
import {SvmService} from "services/svm.service";
import {Fungible, UserService} from "services/user.service";
import {assetValidator} from "validators/asset.validator";
import {balanceFeeValidator} from "validators/balance-fee.validator";
import {balanceValidator} from "validators/balance.validator";
import {nameValidator} from "validators/name.validator";
import { FToken } from "../types/f-token.types";

@Component({
  selector: "app-transfer",
  template: `
    <div mat-dialog-title>Transfer {{symbol}}</div>
    <div mat-dialog-content>

      <form id="transferForm" [formGroup]="form" (ngSubmit)="onSubmit()">

        <mat-form-field appearance="standard">
          <mat-label>To</mat-label>
          <input matInput formControlName="to"/>
          <mat-error *ngIf="to.hasError('required')">
            Mustn't be empty
          </mat-error>
          <mat-error *ngIf="to.hasError('minlength')">
            Must contain at least 3 characters
          </mat-error>
          <mat-error *ngIf="to.hasError('maxlength')">
            Mustn't contain more than 12 characters
          </mat-error>
          <mat-error *ngIf="!to.hasError('minlength') && !to.hasError('maxlength') && to.hasError('nameValid')">
            Must only contain a-z characters, 1-5 numbers and . symbol
          </mat-error>
        </mat-form-field>

        <mat-form-field appearance="standard">
          <mat-label>Quantity</mat-label>
          <input matInput formControlName="amount" type="number"/>
          <a matSuffix class="set-max" (click)="setMax()">MAX</a>
          <mat-error *ngIf="amount.hasError('required')">
            Mustn't be empty
          </mat-error>
          <mat-error *ngIf="amount.hasError('min') && !amount.hasError('assetValid')">
            Minimum 0.0001 {{symbol}}
          </mat-error>
          <mat-error *ngIf="amount.hasError('assetValid')">
            Up to four decimal places allowed
          </mat-error>
          <mat-error *ngIf="amount.hasError('balanceValid') && !amount.hasError('assetValid')">
            Insufficient balance
          </mat-error>
          <mat-error *ngIf="amount.hasError('balanceFeeValid') && !amount.hasError('balanceValid') && !amount.hasError('assetValid')">
            Insufficient balance to pay the fees
          </mat-error>
        </mat-form-field>

        <mat-form-field appearance="standard">
          <mat-label>Memo</mat-label>
          <input matInput formControlName="memo">
          <mat-error *ngIf="memo.hasError('maxlength')">
            256 characters maximum
          </mat-error>
        </mat-form-field>

        <mat-checkbox formControlName="isWithdraw">
          Send to Telos account
        </mat-checkbox>

      </form>

      <div class="cards">
        <mat-list dense>
          <mat-list-item>
            FEE <div class="spacer"></div> 0.1000 TLOS
          </mat-list-item>
          <mat-list-item>
            REMAINING <div class="spacer"></div> {{tlosRemaining}}
          </mat-list-item>
        </mat-list>

        <mat-divider></mat-divider>

        <mat-list dense>
          <mat-list-item>
            TRANSFER <div class="spacer"></div> {{total}}
          </mat-list-item>
          <mat-list-item>
            REMAINING <div class="spacer"></div> {{remaining}} {{symbol}}
          </mat-list-item>
        </mat-list>
      </div>

      <mat-progress-bar *ngIf="isLoading" mode="indeterminate"></mat-progress-bar>

    </div>
    <div mat-dialog-actions>
      <button
        mat-stroked-button
        color="primary"
        form="transferForm"
        [disabled]="isLoading || form.invalid">
        TRANSFER
      </button>
    </div>
  `,
  styles: [`
    button {
      width: 100%;
    }

    .set-max {
      color: #448AFF;
      cursor: pointer;
    }
  `]
})
export class TransferComponent {
  public constructor (
    @Inject(MAT_DIALOG_DATA) public readonly token: Fungible,
    private readonly _formBuilder: FormBuilder,
    private readonly _matSnackBar: MatSnackBar,
    private readonly _svmService: SvmService,
    private readonly _userService: UserService
  ) {}

  public readonly symbol = this.token.key.sym.split(",")[1];

  public readonly form = this._formBuilder.nonNullable.group({
    to: ["", [
      Validators.required,
      Validators.minLength(3),
      Validators.maxLength(12),
      nameValidator()
    ]],
    amount: ["", [
      Validators.required,
      Validators.min(0.0001),
      assetValidator(),
      balanceValidator(this.balance),
      // balanceFeeValidator(this.balance, this._svmService.fees.get("VMT")!)
    ]],
    memo: ["", [
      Validators.maxLength(256)
    ]],
    isWithdraw: [false, []]
  });

  public isLoading = false;

  public get to (): FormControl<string> {
    return this.form.controls["to"];
  }

  public get amount (): FormControl<string> {
    return this.form.controls["amount"];
  }

  public get memo (): FormControl<string> {
    return this.form.controls["memo"];
  }

  public get total (): string {
    return `${(parseFloat(this.amount.value ? this.amount.value : "0.0000")).toFixed(4)} ${this.symbol}`
  }

  public get staked (): any {
    return this.token.value.staked;
  }

  public get balance (): any {
    return this.token.value.liquid;
  }

  public get tlosBalance (): any {
    const tlos = this._userService.user.tokens.fungible.find((liquid) => liquid.key.sym.includes("TLOS"));

    if (!tlos) {
      return "0.0000 TLOS";
    }

    return tlos.value.liquid;
  }

  public get tlosRemaining (): any {
    return (parseFloat(this.tlosBalance) - 0.1).toFixed(4) + " TLOS";
  }

  public get quantity (): any {
    return this.amount.value ? parseFloat(this.amount.value).toFixed(4) : "0.0000";
  }

  public get remaining (): string {
    return (parseFloat(this.balance) - parseFloat(this.amount.value ? this.amount.value : "0.0000 VMT")).toFixed(4);
  }

  public setMax (): void {
    const max = (parseFloat(this.amount.value ? this.amount.value : "0.0000 VMT") + parseFloat(this.remaining)).toFixed(4);

    this.amount.setValue(max);
  }

  public async onSubmit (): Promise<void> {
    this.isLoading = true;

    const {_svmService, _userService, form} = this;
    const {to, amount, memo, isWithdraw} = form.value;
    const {privateKey} = _userService;
    const {name, nonce} = _userService.user.profile;
    const from = name;
    const signature = _svmService.sign(`${nonce}`, privateKey);

    if (!to || !amount) {
      this.isLoading = false;
      return;
    }

    const quantity = `${parseFloat(amount).toFixed(4)} ${this.symbol}`;

    const handle = (error: any): void => {
      this._matSnackBar.open(error, "", {duration: 7000});
    };

    const transaction = await _svmService.push(
      "transfer",
      {from, to, quantity: {quantity, contract: this.token.key.contract}, memo, signature, isWithdraw}
    ).catch(handle);

    if (!transaction) {
      this.isLoading = false;
      return;
    }

    await _userService.reloadUser();

    this._matSnackBar.open(`Sent ${quantity} to ${to}`, "OK");
    this.isLoading = false;
  }
}
